### ISSUE TITLE
Kirby Starterkit

### ISSUE THREAD

**Issue by findthebug** [beebmx/kirby-pay#2]
i get an error after setup, if i try to login to the panel.
to reproduce:
- downloaded the kirby starterkit
- run kirby-pay composer (finished without any errors)
<img width="917" alt="Bildschirmfoto 2020-06-08 um 14 17 37" src="https://user-images.githubusercontent.com/5121132/84029688-140e7580-a993-11ea-9f08-341a289c4d2d.png">
- vagrant with proper vhost setup / latest osx

**Comment by findthebug** [comment]
its because of php version. it need 7.3 i used 7.2

**Comment by beebmx** [comment]
Sure.
You can see the requirements in the [documentation](https://beebmx.github.io/kirby-pay/guide/#requirements)
